services:
  - type: web
    name: pong-server
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    headers:
      - path: /*
        values:
          Access-Control-Allow-Origin: https://asuhantsev.github.io
          Access-Control-Allow-Methods: GET, POST, OPTIONS
          Access-Control-Allow-Headers: Content-Type
          Access-Control-Allow-Credentials: true
          Strict-Transport-Security: max-age=31536000; includeSubDomains
    routes:
      - type: rewrite
        source: /socket.io/*
        destination: /socket.io/$1
    healthCheckPath: /health
    websocket: true