services:
  - type: web
    name: pong-server
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    headers:
      - path: /*
        values:
          Cache-Control: no-cache
          Connection: keep-alive